### ISSUE TITLE
Code in README is out of date

### ISSUE THREAD

**Issue by sethladd** [pylaligand/dart-sqlite#14] opened 2016-04-06 16:36 UTC
Dart doesn't use the `#import` syntax anymore.

**Comment by pylaligand** [comment] 2016-04-06 17:27
This is so totally a dupe of #9 :stuck_out_tongue:

**Comment by pylaligand** [comment] 2016-04-06 17:27
And #11 will offer some actionable examples.

**Closed by pylaligand** 2016-04-06 17:27 UTC
